### PR TITLE
Make better test model for fbos

### PR DESCRIPTION
**Pull request by Dolphin2Point1**
Hydos cant 3d model

### CODE REVIEW

**Comment by hYdos** [comment]
based. why is it a draft?

**Comment by Dolphin2Point1** [comment]
i havent added the trees and bushes yet and ive decided not to use particles because i dont know how to use them

**Comment by hYdos** [comment]
ah. even more based

**Comment by Dolphin2Point1** [comment]
im adding seven meter trees :rofl:

**Comment by Dolphin2Point1** [comment]
i dont really feel like adding bushes i have to go to bed soon anyways

**Comment by Dolphin2Point1** [comment]
bushes arent really important

**Comment by Dolphin2Point1** [comment]
k

**Pull request merged**
